name: Discord Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord Notify
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"<@&1417241810379608204>\",
            \"embeds\": [
              {
                \"title\": \"Nexora APV Update\",
                \"description\": \"${{ github.event.head_commit.message }}\",
                \"color\": 14859818,
                \"thumbnail\": {
                  \"url\": \"https://raw.githubusercontent.com/NexoraRoleplayNL/NexoraRoleplayAPV/main/docs/assets/logo.png\"
                },
                \"fields\": [
                {
                  "name": "Gwijzigd Door",
                  "value": "Nexora Development",
                  "inline": true
                  }
                ],
                \"footer\": {
                  \"text\": \"Nexora Roleplay • 2026\"
                }
              }
            ]
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}