name: Discord Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Nexora Roleplay
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"<@&1417241810379608204>\",
            \"embeds\": [
              {
                \"title\": \"🚨 Nexora APV Update\",
                \"description\": \"${{ github.event.head_commit.message }}\",
                \"color\": 5814783,
                \"fields\": [
                  {
                    \"name\": \"👤 Door\",
                    \"value\": \"${{ github.actor }}\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"🌍 Website\",
                    \"value\": \"https://NexoraRoleplayNL.github.io/NexoraRoleplayAPV/\"
                  }
                ],
                \"footer\": {
                  \"text\": \"Nexora Roleplay • APV System\"
                }
              }
            ]
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}